### ISSUE TITLE
Provide asset with net-snmp?

### ISSUE THREAD

**Issue by nixwiz** [nixwiz/sensu-perl-runtime#7]
Should I provide a separate copy of the assets/docker images with net-snmp enabled?  Or should it be enabled by default?

Thoughts @meni2029?

**Comment by meni2029** [comment]
I’ve been thinking about that. My last thought was to make two different assets, as net-snmp adds extra MBytes. One might want to limit size of the asset if snmp is not involved.
If you think it’s simpler to have just one, then I’m fine with that too. 
Cheers
